import os
os.system ('clear')
os.system ('clear')                                                                                  
os.system ('sl')
os.system('clear')
print ('\033[1;36mحﺎﭴﻧﺑ مﺗ')
os.system ('figlet HK instagram')
print ("")
print ("")
print (" \033[1;32m بﺎﺴﺤ مﺴإ  \033[1;33m: me_hdi_el7")
print ("")
print ("")
print (" \033[1;32mفﺗﺎﮩﻟ مﻗر/ ﺪﯾﺮﺑ \033[1;33m: errors : IPhone os")
print ("")
print ("")
print (" \033[1;32mةﺮﻏﺗ :\033[1;33m errors : IPhone os")
print ("")
print ("")
os.system ('figlet')

